roles = ["frontend"]

[directories]
app = "frontend"

auth_callback_path = ["/custom/path1", "/custom/path2"]

webhooks_path = "/api/webhooks"

[commands]
dev = "npm --prefix frontend run dev"
build = "npm --prefix frontend run build"
